    version: '3'
     
    services:
        node1:
            build:
                context: ./docker
                args:
                    SSH_MASTER_USER: ${SSH_MASTER_USER}
                    SSH_MASTER_PASS: ${SSH_MASTER_PASS}
            hostname: server
            ports:
                - "2222:22"

        node2:
            build:
                context: ./docker
                args:
                    SSH_MASTER_USER: ${SSH_MASTER_USER}
                    SSH_MASTER_PASS: ${SSH_MASTER_PASS}
            hostname: server
            ports:
                - "3333:22"
        node3:
            build:
                context: ./docker
                args:
                    SSH_MASTER_USER: ${SSH_MASTER_USER}
                    SSH_MASTER_PASS: ${SSH_MASTER_PASS}
            hostname: server
            ports:
                - "4444:22"
