    version: '3'
     
    services:
        server1:
            build:
                context: ./docker
                args:
                    SSH_MASTER_USER: ${SSH_MASTER_USER}
                    SSH_MASTER_PASS: ${SSH_MASTER_PASS}
            hostname: server
            ports:
                - "2222:22"

        server2:
            build:
                context: ./docker
                args:
                    SSH_MASTER_USER: ${SSH_MASTER_USER}
                    SSH_MASTER_PASS: ${SSH_MASTER_PASS}
            hostname: server
            ports:
                - "3333:22"
